### PR TITLE
Repo File Sync: MuDevOpsWrapper.yml - Add code coverage calculation parameter

### PR DESCRIPTION
**Pull request by uefibot**
synced local file(s) with [microsoft/mu_devops](https://github.com/microsoft/mu_devops).

🤖: View the [Repo File Sync Configuration File](https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml) to see how files are synced.

---

This PR was created automatically by the [repo-file-sync-action](https://github.com/BetaHuhn/repo-file-sync-action) workflow run [#6774774926](https://github.com/microsoft/mu_devops/actions/runs/6774774926)

### CODE REVIEW

**Review by makubacki — APPROVED** [review]

**Comment by makubacki** [comment]
Waiting for the sync to be amended after https://github.com/microsoft/mu_devops/pull/268 is completed.

**Review by Javagedes — APPROVED** [review]

**Pull request merged**
