### PR TITLE
MdePkg: Create Google Test mock library and protocol

### PR DESCRIPTION
**Pull request by v-chhsieh**
## Description

This patch creates a gmock for the MpService function, which is used by CI testing.

For details on how to complete to complete these options and their meaning refer to [CONTRIBUTING.md](https://github.com/microsoft/mu/blob/HEAD/CONTRIBUTING.md).

- [ ] Impacts functionality?
- [ ] Impacts security?
- [ ] Breaking change?
- [x] Includes tests?
- [ ] Includes documentation?

## How This Was Tested

Unit tests component can call these mock functions success

## Integration Instructions

N/A

### CODE REVIEW

**Comment by v-chhsieh** [comment]
@microsoft-github-policy-service agree company="Phoenix"

**Comment by os-d** [comment]
@v-chhsieh, can you take this PR directly to edk2? They have a PR process now and we are updating our process to take as many PRs directly to edk2 (if it makes sense) and then will cherry-pick them back into Project Mu. This will have less churn on the consumer if edk2 wants changes in the PR, etc., the consumer of Project Mu won't have to make changes

**Comment by v-chhsieh** [comment]
> @v-chhsieh, can you take this PR directly to edk2? They have a PR process now and we are updating our process to take as many PRs directly to edk2 (if it makes sense) and then will cherry-pick them back into Project Mu. This will have less churn on the consumer if edk2 wants changes in the PR, etc., the consumer of Project Mu won't have to make changes

Yes, no problem.

**Comment by v-chhsieh** [comment]
I am working to collect and update the other mock for this PR, so I don't need to submit another mock PR again.

**Pull request closed without merging**
