### PR TITLE
Repo File Sync: Add release drafter workflow [Rebase & FF]

### PR DESCRIPTION
**Pull request by uefibot**
synced local file(s) with [microsoft/mu_devops](https://github.com/microsoft/mu_devops).

🤖: View the [Repo File Sync Configuration File](https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml) to see how files are synced.

---

Brings the "release drafter" workflow from [mu_devops](https://github.com/microsoft/mu_devops)
to this repo so automated semantic versioning and release note drafting can be performed here.

---

This PR was created automatically by the [repo-file-sync-action](https://github.com/BetaHuhn/repo-file-sync-action) workflow run [#4682780597](https://github.com/microsoft/mu_devops/actions/runs/4682780597)

### CODE REVIEW

**Comment by makubacki** [comment]
I'll add on a commit to update the repo readme to explain the mu_basecore versioning scheme.

**Comment by makubacki** [comment]
> I'll add on a commit to update the repo readme to explain the mu_basecore versioning scheme.

Done

**Review by os-d — APPROVED** [review]
I assume we will do a release after this is in for a baseline? i.e. the last release is old and the documentation says the ideal case is to consume a release.

**Review by apop5 — APPROVED** [review]

**Comment by makubacki** [comment]
> I assume we will do a release after this is in for a baseline? i.e. the last release is old and the documentation says the ideal case is to consume a release.

Yes. Right after this goes in, the first release will be made.

**Pull request merged**
